---
# - name: Create prometheus directories
#   file:
#     path: "{{ prometheus_dir }}"
#     state: directory
#     owner: root
#     group: root
#     mode: "0755"

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ prometheus_dir }}"
    - "{{ prometheus_dir }}/data"
    - "{{ prometheus_dir }}/alert-rules"

- name: Copy prometheus service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: "0755"

- name: Copy prometheus config file
  template:
    src: prometheus.yml.j2
    dest: /data/prometheus/prometheus.yml
    owner: root
    group: root
    mode: "0755"

- name: Start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
